local runner = require('tests.runner')
local assert = require('tests.helpers.assertions')
local mocks = require('tests.mocks')

local describe, it, before_each = runner.describe, runner.it, runner.before_each

describe('config/management', function()
  local management

  before_each(function()
    mocks.setup()
    mocks.clear_package_cache()
    management = require('luxmotion.config.management')
    management.reset()
  end)

  it('exports all required functions', function()
    assert.is_type(management.get, 'function')
    assert.is_type(management.get_cursor, 'function')
    assert.is_type(management.get_scroll, 'function')
    assert.is_type(management.get_keymaps, 'function')
    assert.is_type(management.get_performance, 'function')
    assert.is_type(management.update, 'function')
    assert.is_type(management.reset, 'function')
  end)

  it('get() returns full config after reset', function()
    local config = management.get()
    assert.is_not_nil(config)
    assert.has_key(config, 'cursor')
    assert.has_key(config, 'scroll')
    assert.has_key(config, 'keymaps')
    assert.has_key(config, 'performance')
  end)

  it('get_cursor() returns cursor config', function()
    local cursor = management.get_cursor()
    assert.is_not_nil(cursor)
    assert.equals(cursor.duration, 250)
    assert.equals(cursor.easing, 'ease-out')
    assert.equals(cursor.enabled, true)
  end)

  it('get_scroll() returns scroll config', function()
    local scroll = management.get_scroll()
    assert.is_not_nil(scroll)
    assert.equals(scroll.duration, 400)
    assert.equals(scroll.easing, 'ease-out')
    assert.equals(scroll.enabled, true)
  end)

  it('get_keymaps() returns keymaps config', function()
    local keymaps = management.get_keymaps()
    assert.is_not_nil(keymaps)
    assert.equals(keymaps.cursor, true)
    assert.equals(keymaps.scroll, true)
    assert.equals(keymaps.experimental, false)
  end)

  it('get_performance() returns performance config', function()
    local perf = management.get_performance()
    assert.is_not_nil(perf)
    assert.equals(perf.enabled, false)
    assert.equals(perf.large_file_threshold, 5000)
  end)

  it('get() with category returns specific section', function()
    local cursor = management.get('cursor')
    assert.equals(cursor.duration, 250)

    local scroll = management.get('scroll')
    assert.equals(scroll.duration, 400)

    local keymaps = management.get('keymaps')
    assert.equals(keymaps.cursor, true)

    local perf = management.get('performance')
    assert.equals(perf.enabled, false)
  end)

  it('update() merges cursor config', function()
    management.update({ cursor = { duration = 500 } })
    local cursor = management.get_cursor()
    assert.equals(cursor.duration, 500)
    assert.equals(cursor.easing, 'ease-out')
    assert.equals(cursor.enabled, true)
  end)

  it('update() merges scroll config', function()
    management.update({ scroll = { easing = 'linear', enabled = false } })
    local scroll = management.get_scroll()
    assert.equals(scroll.duration, 400)
    assert.equals(scroll.easing, 'linear')
    assert.equals(scroll.enabled, false)
  end)

  it('update() merges keymaps config', function()
    management.update({ keymaps = { experimental = true } })
    local keymaps = management.get_keymaps()
    assert.equals(keymaps.cursor, true)
    assert.equals(keymaps.scroll, true)
    assert.equals(keymaps.experimental, true)
  end)

  it('update() merges performance config', function()
    management.update({ performance = { enabled = true, large_file_threshold = 10000 } })
    local perf = management.get_performance()
    assert.equals(perf.enabled, true)
    assert.equals(perf.large_file_threshold, 10000)
    assert.equals(perf.disable_syntax_during_scroll, true)
  end)

  it('update() handles multiple sections at once', function()
    management.update({
      cursor = { duration = 100 },
      scroll = { duration = 200 },
      keymaps = { cursor = false },
    })
    assert.equals(management.get_cursor().duration, 100)
    assert.equals(management.get_scroll().duration, 200)
    assert.equals(management.get_keymaps().cursor, false)
  end)

  it('update() with empty config does not change anything', function()
    local before = management.get()
    management.update({})
    local after = management.get()
    assert.equals(before.cursor.duration, after.cursor.duration)
    assert.equals(before.scroll.duration, after.scroll.duration)
  end)

  it('update() with nil does not crash', function()
    assert.does_not_throw(function()
      management.update(nil)
    end)
  end)

  it('reset() restores default values', function()
    management.update({
      cursor = { duration = 999, easing = 'linear', enabled = false },
      scroll = { duration = 888, easing = 'ease-in', enabled = false },
    })
    management.reset()
    local cursor = management.get_cursor()
    local scroll = management.get_scroll()
    assert.equals(cursor.duration, 250)
    assert.equals(cursor.easing, 'ease-out')
    assert.equals(cursor.enabled, true)
    assert.equals(scroll.duration, 400)
    assert.equals(scroll.easing, 'ease-out')
    assert.equals(scroll.enabled, true)
  end)

  it('get() returns config consistently', function()
    local config1 = management.get()
    assert.equals(config1.cursor.duration, 250)
    local config2 = management.get()
    assert.equals(config2.cursor.duration, 250)
  end)

  it('consecutive updates accumulate', function()
    management.update({ cursor = { duration = 100 } })
    management.update({ cursor = { easing = 'linear' } })
    management.update({ cursor = { enabled = false } })
    local cursor = management.get_cursor()
    assert.equals(cursor.duration, 100)
    assert.equals(cursor.easing, 'linear')
    assert.equals(cursor.enabled, false)
  end)
end)
