local runner = require('tests.runner')
local assert = require('tests.helpers.assertions')
local mocks = require('tests.mocks')

local describe, it, before_each = runner.describe, runner.it, runner.before_each

describe('trail/highlights', function()
  local highlights

  before_each(function()
    mocks.setup()
    mocks.clear_package_cache()
    highlights = require('luxmotion.trail.highlights')
  end)

  it('exports all required functions', function()
    assert.is_type(highlights.setup, 'function')
    assert.is_type(highlights.teardown, 'function')
    assert.is_type(highlights.get_group_name, 'function')
    assert.is_type(highlights.blend_hex, 'function')
    assert.is_type(highlights.parse_hex, 'function')
    assert.is_type(highlights.to_hex, 'function')
  end)

  it('parse_hex converts hex string to RGB table', function()
    local r, g, b = highlights.parse_hex('#FF8800')
    assert.equals(r, 255)
    assert.equals(g, 136)
    assert.equals(b, 0)
  end)

  it('parse_hex handles lowercase', function()
    local r, g, b = highlights.parse_hex('#ff8800')
    assert.equals(r, 255)
    assert.equals(g, 136)
    assert.equals(b, 0)
  end)

  it('parse_hex handles black', function()
    local r, g, b = highlights.parse_hex('#000000')
    assert.equals(r, 0)
    assert.equals(g, 0)
    assert.equals(b, 0)
  end)

  it('parse_hex handles white', function()
    local r, g, b = highlights.parse_hex('#FFFFFF')
    assert.equals(r, 255)
    assert.equals(g, 255)
    assert.equals(b, 255)
  end)

  it('to_hex converts RGB to hex string', function()
    local hex = highlights.to_hex(255, 136, 0)
    assert.equals(hex, '#FF8800')
  end)

  it('to_hex handles zeros', function()
    local hex = highlights.to_hex(0, 0, 0)
    assert.equals(hex, '#000000')
  end)

  it('to_hex clamps values above 255', function()
    local hex = highlights.to_hex(300, 0, 0)
    assert.equals(hex, '#FF0000')
  end)

  it('to_hex clamps values below 0', function()
    local hex = highlights.to_hex(-10, 0, 0)
    assert.equals(hex, '#000000')
  end)

  it('blend_hex blends two colors at 0.0', function()
    local result = highlights.blend_hex('#FF0000', '#0000FF', 0.0)
    assert.equals(result, '#0000FF')
  end)

  it('blend_hex blends two colors at 1.0', function()
    local result = highlights.blend_hex('#FF0000', '#0000FF', 1.0)
    assert.equals(result, '#FF0000')
  end)

  it('blend_hex blends two colors at 0.5', function()
    local result = highlights.blend_hex('#FF0000', '#000000', 0.5)
    local r, g, b = highlights.parse_hex(result)
    assert.equals(r, 128)
    assert.equals(g, 0)
    assert.equals(b, 0)
  end)

  it('blend_hex blends white to black at 0.5', function()
    local result = highlights.blend_hex('#FFFFFF', '#000000', 0.5)
    local r, g, b = highlights.parse_hex(result)
    assert.equals(r, 128)
    assert.equals(g, 128)
    assert.equals(b, 128)
  end)

  it('get_group_name returns correct name for index', function()
    assert.equals(highlights.get_group_name(1), 'LuxMotionTrail1')
    assert.equals(highlights.get_group_name(3), 'LuxMotionTrail3')
    assert.equals(highlights.get_group_name(6), 'LuxMotionTrail6')
  end)

  it('setup creates highlight groups', function()
    highlights.setup('#FF0000', '#000000', 6)
    local hl_state = mocks.get_highlights()
    assert.is_not_nil(hl_state['LuxMotionTrail1'])
    assert.is_not_nil(hl_state['LuxMotionTrail6'])
  end)

  it('setup creates correct number of highlight groups', function()
    highlights.setup('#FF0000', '#000000', 4)
    local hl_state = mocks.get_highlights()
    assert.is_not_nil(hl_state['LuxMotionTrail1'])
    assert.is_not_nil(hl_state['LuxMotionTrail4'])
    assert.is_nil(hl_state['LuxMotionTrail5'])
  end)

  it('setup groups have decreasing intensity', function()
    highlights.setup('#FF0000', '#000000', 6)
    local hl_state = mocks.get_highlights()
    local r1, _, _ = highlights.parse_hex(hl_state['LuxMotionTrail1'].val.bg)
    local r6, _, _ = highlights.parse_hex(hl_state['LuxMotionTrail6'].val.bg)
    assert.greater_than(r1, r6)
  end)

  it('setup brightest group is close to trail color', function()
    highlights.setup('#FF0000', '#000000', 6)
    local hl_state = mocks.get_highlights()
    local r, _, _ = highlights.parse_hex(hl_state['LuxMotionTrail1'].val.bg)
    assert.greater_than(r, 200)
  end)

  it('setup dimmest group is close to background', function()
    highlights.setup('#FF0000', '#000000', 6)
    local hl_state = mocks.get_highlights()
    local r, _, _ = highlights.parse_hex(hl_state['LuxMotionTrail6'].val.bg)
    assert.less_than(r, 30)
  end)

  it('teardown is callable', function()
    highlights.setup('#FF0000', '#000000', 6)
    assert.does_not_throw(function()
      highlights.teardown()
    end)
  end)
end)
