local runner = require('tests.runner')
local assert = require('tests.helpers.assertions')
local mocks = require('tests.mocks')

local describe, it, before_each = runner.describe, runner.it, runner.before_each

describe('trail/renderer', function()
  local renderer

  before_each(function()
    mocks.setup()
    mocks.clear_package_cache()
    mocks.set_buffer_content({
      "line 1", "line 2", "line 3", "line 4", "line 5",
      "line 6", "line 7", "line 8", "line 9", "line 10",
    })
    renderer = require('luxmotion.trail.renderer')
  end)

  it('exports all required functions', function()
    assert.is_type(renderer.reset, 'function')
    assert.is_type(renderer.push_position, 'function')
    assert.is_type(renderer.render, 'function')
    assert.is_type(renderer.clear, 'function')
    assert.is_type(renderer.get_namespace_id, 'function')
    assert.is_type(renderer.get_positions, 'function')
  end)

  it('get_namespace_id returns a number', function()
    local ns = renderer.get_namespace_id()
    assert.is_type(ns, 'number')
  end)

  it('get_namespace_id returns same value on repeated calls', function()
    local ns1 = renderer.get_namespace_id()
    local ns2 = renderer.get_namespace_id()
    assert.equals(ns1, ns2)
  end)

  it('reset clears position buffer', function()
    renderer.push_position(1, { cursor = { line = 5, col = 3 } }, 6)
    renderer.reset()
    local positions = renderer.get_positions()
    assert.length(positions, 0)
  end)

  it('push_position adds position to buffer', function()
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 5, col = 3 } }, 6)
    local positions = renderer.get_positions()
    assert.length(positions, 1)
    assert.equals(positions[1].line, 5)
    assert.equals(positions[1].col, 3)
  end)

  it('push_position trims to max_length', function()
    renderer.reset()
    for i = 1, 10 do
      renderer.push_position(1, { cursor = { line = i, col = 0 } }, 4)
    end
    local positions = renderer.get_positions()
    assert.length(positions, 4)
  end)

  it('push_position keeps newest positions', function()
    renderer.reset()
    for i = 1, 8 do
      renderer.push_position(1, { cursor = { line = i, col = 0 } }, 4)
    end
    local positions = renderer.get_positions()
    assert.equals(positions[1].line, 8)
    assert.equals(positions[4].line, 5)
  end)

  it('push_position deduplicates consecutive same position', function()
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 5, col = 3 } }, 6)
    renderer.push_position(1, { cursor = { line = 5, col = 3 } }, 6)
    renderer.push_position(1, { cursor = { line = 5, col = 3 } }, 6)
    local positions = renderer.get_positions()
    assert.length(positions, 1)
  end)

  it('push_position allows non-consecutive duplicate', function()
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 5, col = 3 } }, 6)
    renderer.push_position(1, { cursor = { line = 6, col = 3 } }, 6)
    renderer.push_position(1, { cursor = { line = 5, col = 3 } }, 6)
    local positions = renderer.get_positions()
    assert.length(positions, 3)
  end)

  it('render places extmarks', function()
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 3, col = 2 } }, 6)
    renderer.push_position(1, { cursor = { line = 4, col = 2 } }, 6)
    renderer.render(1, 6)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.greater_than(#extmarks, 0)
  end)

  it('render clears previous extmarks before placing new ones', function()
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 3, col = 2 } }, 6)
    renderer.render(1, 6)
    local ns = renderer.get_namespace_id()
    local first_count = #mocks.get_extmarks(ns)

    renderer.push_position(1, { cursor = { line = 4, col = 2 } }, 6)
    renderer.render(1, 6)
    local second_count = #mocks.get_extmarks(ns)

    assert.equals(second_count, 2)
  end)

  it('render assigns highlight groups in order', function()
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 1, col = 0 } }, 3)
    renderer.push_position(1, { cursor = { line = 2, col = 0 } }, 3)
    renderer.push_position(1, { cursor = { line = 3, col = 0 } }, 3)
    renderer.render(1, 3)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.equals(extmarks[1].opts.hl_group, 'LuxMotionTrail1')
    assert.equals(extmarks[3].opts.hl_group, 'LuxMotionTrail3')
  end)

  it('clear removes all extmarks', function()
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 3, col = 2 } }, 6)
    renderer.render(1, 6)
    renderer.clear(1)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.length(extmarks, 0)
  end)

  it('clear also resets position buffer', function()
    renderer.push_position(1, { cursor = { line = 3, col = 2 } }, 6)
    renderer.clear(1)
    local positions = renderer.get_positions()
    assert.length(positions, 0)
  end)

  it('render with empty positions does nothing', function()
    renderer.reset()
    assert.does_not_throw(function()
      renderer.render(1, 6)
    end)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.length(extmarks, 0)
  end)

  it('render uses 0-indexed lines for extmarks', function()
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 5, col = 3 } }, 6)
    renderer.render(1, 6)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.equals(extmarks[1].line, 4)
  end)

  it('render clamps col when cursor is at end of line', function()
    mocks.set_buffer_content({ "abc" })
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 1, col = 2 } }, 6)
    renderer.render(1, 6)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.length(extmarks, 1)
    assert.equals(extmarks[1].col, 2)
    assert.equals(extmarks[1].opts.end_col, 3)
  end)

  it('render handles col beyond line length', function()
    mocks.set_buffer_content({ "ab" })
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 1, col = 10 } }, 6)
    assert.does_not_throw(function()
      renderer.render(1, 6)
    end)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.length(extmarks, 1)
    assert.equals(extmarks[1].col, 1)
    assert.equals(extmarks[1].opts.end_col, 2)
  end)

  it('render skips empty lines', function()
    mocks.set_buffer_content({ "" })
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 1, col = 0 } }, 6)
    assert.does_not_throw(function()
      renderer.render(1, 6)
    end)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.length(extmarks, 0)
  end)

  it('render skips positions beyond buffer line count', function()
    mocks.set_buffer_content({ "line 1", "line 2" })
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 5, col = 0 } }, 6)
    assert.does_not_throw(function()
      renderer.render(1, 6)
    end)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.length(extmarks, 0)
  end)

  it('render skips positions with line zero', function()
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 0, col = 0 } }, 6)
    assert.does_not_throw(function()
      renderer.render(1, 6)
    end)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.length(extmarks, 0)
  end)

  it('render places valid extmarks and skips invalid in same batch', function()
    mocks.set_buffer_content({ "hello", "", "world" })
    renderer.reset()
    renderer.push_position(1, { cursor = { line = 3, col = 0 } }, 6)
    renderer.push_position(1, { cursor = { line = 2, col = 0 } }, 6)
    renderer.push_position(1, { cursor = { line = 1, col = 0 } }, 6)
    renderer.render(1, 6)
    local ns = renderer.get_namespace_id()
    local extmarks = mocks.get_extmarks(ns)
    assert.length(extmarks, 2)
  end)
end)
