local runner = require('tests.runner')
local assert = require('tests.helpers.assertions')
local mocks = require('tests.mocks')

local describe, it, before_each = runner.describe, runner.it, runner.before_each

describe('context/Context', function()
  local Context

  before_each(function()
    mocks.setup()
    mocks.clear_package_cache()
    mocks.set_buffer_content({
      "line 1",
      "line 2",
      "line 3",
      "line 4",
      "line 5",
    })
    mocks.set_cursor(1, 0)
    mocks.set_window_size(40, 120)
    mocks.set_topline(1)
    Context = require('luxmotion.context.Context')
  end)

  it('new() creates a Context with bufnr and winid', function()
    local ctx = Context.new(1, 1000)
    assert.equals(ctx.bufnr, 1)
    assert.equals(ctx.winid, 1000)
  end)

  it('new() captures starting state', function()
    mocks.set_cursor(3, 5)
    mocks.set_topline(2)
    local ctx = Context.new(1, 1000)
    assert.equals(ctx.start.cursor[1], 3)
    assert.equals(ctx.start.cursor[2], 5)
    assert.equals(ctx.start.topline, 2)
    assert.equals(ctx.start.line_count, 5)
  end)

  it('new() uses current buffer and window if not provided', function()
    local ctx = Context.new()
    assert.is_type(ctx.bufnr, 'number')
    assert.is_type(ctx.winid, 'number')
  end)

  it('is_valid() returns true for valid context', function()
    local ctx = Context.new(1, 1000)
    local valid, reason = ctx:is_valid()
    assert.is_true(valid)
    assert.is_nil(reason)
  end)

  it('is_valid() returns false with reason when buffer is deleted', function()
    local ctx = Context.new(1, 1000)
    mocks.delete_buffer(1)
    local valid, reason = ctx:is_valid()
    assert.is_false(valid)
    assert.equals(reason, 'buffer_deleted')
  end)

  it('is_valid() returns false with reason when window is closed', function()
    local ctx = Context.new(1, 1000)
    mocks.close_window(1000)
    local valid, reason = ctx:is_valid()
    assert.is_false(valid)
    assert.equals(reason, 'window_closed')
  end)

  it('is_valid() returns false with reason when buffer changed in window', function()
    local ctx = Context.new(1, 1000)
    mocks.set_window_buffer(1000, 2)
    local valid, reason = ctx:is_valid()
    assert.is_false(valid)
    assert.equals(reason, 'buffer_changed')
  end)

  it('get_line_count() returns current buffer line count', function()
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:get_line_count(), 5)
  end)

  it('get_line_count() returns fresh count after buffer changes', function()
    local ctx = Context.new(1, 1000)
    mocks.set_buffer_content({ "a", "b", "c" })
    assert.equals(ctx:get_line_count(), 3)
  end)

  it('get_line_length() returns length of specified line', function()
    mocks.set_buffer_content({ "abc", "defgh", "ij" })
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:get_line_length(1), 3)
    assert.equals(ctx:get_line_length(2), 5)
    assert.equals(ctx:get_line_length(3), 2)
  end)

  it('get_line_length() returns 0 for empty line', function()
    mocks.set_buffer_content({ "", "abc", "" })
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:get_line_length(1), 0)
    assert.equals(ctx:get_line_length(3), 0)
  end)

  it('get_line_length() returns 0 for non-existent line', function()
    mocks.set_buffer_content({ "abc" })
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:get_line_length(99), 0)
  end)

  it('clamp_line() returns line within valid range', function()
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:clamp_line(1), 1)
    assert.equals(ctx:clamp_line(3), 3)
    assert.equals(ctx:clamp_line(5), 5)
  end)

  it('clamp_line() clamps line below minimum to 1', function()
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:clamp_line(0), 1)
    assert.equals(ctx:clamp_line(-5), 1)
  end)

  it('clamp_line() clamps line above maximum to line count', function()
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:clamp_line(10), 5)
    assert.equals(ctx:clamp_line(100), 5)
  end)

  it('clamp_line() uses fresh line count', function()
    local ctx = Context.new(1, 1000)
    mocks.set_buffer_content({ "a", "b", "c" })
    assert.equals(ctx:clamp_line(5), 3)
  end)

  it('clamp_column() returns column within valid range', function()
    mocks.set_buffer_content({ "abcdef" })
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:clamp_column(0, 1), 0)
    assert.equals(ctx:clamp_column(3, 1), 3)
    assert.equals(ctx:clamp_column(5, 1), 5)
  end)

  it('clamp_column() clamps column below minimum to 0', function()
    mocks.set_buffer_content({ "abcdef" })
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:clamp_column(-1, 1), 0)
    assert.equals(ctx:clamp_column(-10, 1), 0)
  end)

  it('clamp_column() clamps column above maximum to line_length - 1', function()
    mocks.set_buffer_content({ "abcdef" })
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:clamp_column(10, 1), 5)
    assert.equals(ctx:clamp_column(100, 1), 5)
  end)

  it('clamp_column() handles empty line', function()
    mocks.set_buffer_content({ "" })
    local ctx = Context.new(1, 1000)
    assert.equals(ctx:clamp_column(0, 1), 0)
    assert.equals(ctx:clamp_column(5, 1), 0)
  end)

  it('clamp_position() clamps both line and column', function()
    mocks.set_buffer_content({ "abc", "defgh", "ij" })
    local ctx = Context.new(1, 1000)
    local line, col = ctx:clamp_position(2, 3)
    assert.equals(line, 2)
    assert.equals(col, 3)
  end)

  it('clamp_position() clamps line first then column for that line', function()
    mocks.set_buffer_content({ "abc", "defgh", "ij" })
    local ctx = Context.new(1, 1000)
    local line, col = ctx:clamp_position(10, 10)
    assert.equals(line, 3)
    assert.equals(col, 1)
  end)

  it('set_cursor() sets cursor position in context window', function()
    local ctx = Context.new(1, 1000)
    local success = ctx:set_cursor(3, 2)
    assert.is_true(success)
    local cursor = mocks.get_cursor()
    assert.equals(cursor[1], 3)
    assert.equals(cursor[2], 2)
  end)

  it('set_cursor() clamps position before setting', function()
    local ctx = Context.new(1, 1000)
    ctx:set_cursor(100, 100)
    local cursor = mocks.get_cursor()
    assert.equals(cursor[1], 5)
  end)

  it('set_cursor() returns false with reason if context invalid', function()
    local ctx = Context.new(1, 1000)
    mocks.delete_buffer(1)
    local success, reason = ctx:set_cursor(3, 2)
    assert.is_false(success)
    assert.equals(reason, 'buffer_deleted')
  end)

  it('set_cursor() does not modify cursor if context invalid', function()
    mocks.set_cursor(1, 0)
    local ctx = Context.new(1, 1000)
    mocks.delete_buffer(1)
    ctx:set_cursor(5, 5)
    local cursor = mocks.get_cursor()
    assert.equals(cursor[1], 1)
    assert.equals(cursor[2], 0)
  end)

  it('restore_view() restores topline and cursor position', function()
    local ctx = Context.new(1, 1000)
    local success = ctx:restore_view(5, 10, 3)
    assert.is_true(success)
  end)

  it('restore_view() returns false with reason if context invalid', function()
    local ctx = Context.new(1, 1000)
    mocks.close_window(1000)
    local success, reason = ctx:restore_view(5, 10, 3)
    assert.is_false(success)
    assert.equals(reason, 'window_closed')
  end)
end)
